name: stats
on:
  push:
  schedule:
    - cron: "0 0 * * *"

jobs:
  update:
    name: Update stats card
    runs-on: ubuntu-latest
    steps:
      - uses: datarootsio/github-stats-card@v1
        with:
          username: pieterherman-dev
          gh_token_stats: ${{ secrets.TOKEN_STATS }}
          gh_token_commits: ${{ secrets.GITHUB_TOKEN }}
          badge_path: assets/badge.svg
          header: "👋 hi i'm"
          about: "Full Stack Developer from Antwerp."
          theme: hypnotoad
          commit_message: Badge generated.
